#!/usr/bin/env bash
# Build cap-y Docker images with automatic platform and GPU architecture detection.
#
# Architecture is detected automatically by Docker via TARGETARCH (amd64/arm64).
# A single set of Dockerfiles under docker/ handles both arches using multi-stage
# builds and inline uname -m checks. No PLATFORM_ARCH variable needed.
#
# CUDA_ARCH_BIN is the GPU compute capability for source-compiled components:
#   11.0  Jetson Thor / GB10 (default on aarch64)
#   8.9   RTX 4080/4090 (default on x86_64)
#   9.0   H100 / A100 (x86_64)
#   12.0  RTX 5090 Blackwell desktop (x86_64)
#
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-docker/docker-compose.capx.yml}"
CUDA_ARCH_BIN=""
BUILD_ALL=0
BUILD_DEV=0
PUSH=0
PUSH_ONLY=0
REGISTRY="${REGISTRY:-sevapru/cap-y}"

usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --cuda-arch CAP   GPU compute capability (e.g. 8.9, 9.0, 11.0, 12.0)
                    Default: auto-detect via nvidia-smi
  --file FILE       Compose file (default: docker/docker-compose.capx.yml)
  --all             Build all images: base → default, base → open → nvidia
  --dev             Build cap-y:dev after base (all extras + sim venvs)
  --push            Build + tag with arch suffix + push to \$REGISTRY
  --push-only       Tag and push existing local images (no rebuild)
  --registry REPO   Override registry repo (default: sevapru/cap-y)
  -h, --help        Show this help

Architecture is detected automatically by Docker (TARGETARCH = amd64 or arm64).
No --platform flag needed. To cross-build: docker buildx build --platform linux/arm64

Image hierarchy:
  cap-y:base    MIT/Apache clean foundation (mink, DemoGrasp, rh56, OpenCV CUDA, JAX)
  cap-y:default + cuRobo + ContactGraspNet (NVIDIA NC — research only)
  cap-y:open    + ROS2 full stack + nvblox + Drake (from cap-y:base)
  cap-y:nvidia  + Isaac ROS + cuMotion + cuVSLAM (from cap-y:open)

Examples:
  ./docker/build.sh                        # auto-detect GPU, native arch
  ./docker/build.sh --all --cuda-arch 8.9  # full stack, RTX 4090
  ./docker/build.sh --cuda-arch 11.0       # Jetson Thor (when cross-building)
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --cuda-arch)    CUDA_ARCH_BIN="$2"; shift 2 ;;
    --arch)         CUDA_ARCH_BIN="$2"; shift 2 ;;  # legacy alias
    --platform)     echo "NOTE: --platform is no longer needed; Docker detects arch automatically."; shift 2 ;;
    --file|-f)      COMPOSE_FILE="$2"; shift 2 ;;
    --all)          BUILD_ALL=1; shift ;;
    --dev)          BUILD_DEV=1; shift ;;
    --push)         PUSH=1; shift ;;
    --push-only)    PUSH_ONLY=1; PUSH=1; shift ;;
    --registry)     REGISTRY="$2"; shift 2 ;;
    -h|--help)      usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

# ── CUDA architecture detection ───────────────────────────────────────────────
# Platform (x86_64 / aarch64) is handled inside the Dockerfile via TARGETARCH.
# Only CUDA_ARCH_BIN needs to be detected here for cmake-based source builds.
if [[ -z "$CUDA_ARCH_BIN" ]]; then
  if command -v nvidia-smi &>/dev/null; then
    CUDA_ARCH_BIN=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null \
      | head -1 | tr -d '[:space:]') || true
  fi
  if [[ -z "$CUDA_ARCH_BIN" ]]; then
    # Guess from arch: Jetson Thor default for aarch64, RTX 40-series for x86_64
    if [[ "$(uname -m)" == "aarch64" ]]; then
      CUDA_ARCH_BIN="11.0"
    else
      CUDA_ARCH_BIN="8.9"
    fi
    echo "CUDA compute capability: not detected — using default ${CUDA_ARCH_BIN}"
  else
    echo "CUDA compute capability: auto-detected ${CUDA_ARCH_BIN}"
  fi
fi

# ── Write docker/.env (Compose reads this automatically, no manual export needed)
ENV_FILE="$(dirname "${COMPOSE_FILE}")/.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by docker/build.sh — do not commit (already in .gitignore)
CUDA_ARCH_BIN=${CUDA_ARCH_BIN}
EOF

# ── Push helper ───────────────────────────────────────────────────────────────
_push_images() {
  local ARCH
  ARCH="$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"
  echo ""
  echo "Pushing to ${REGISTRY} (arch: ${ARCH})..."
  for img in base default open nvidia dev; do
    if docker image inspect "cap-y:${img}" &>/dev/null; then
      docker tag "cap-y:${img}" "${REGISTRY}:${img}-${ARCH}"
      echo "  pushing ${REGISTRY}:${img}-${ARCH}"
      docker push "${REGISTRY}:${img}-${ARCH}"
    fi
  done
  docker tag "cap-y:open" "${REGISTRY}:latest-${ARCH}" 2>/dev/null && \
    docker push "${REGISTRY}:latest-${ARCH}" && \
    echo "  pushing ${REGISTRY}:latest-${ARCH}"
  echo ""
  echo "Pushed:"
  docker image ls "${REGISTRY}"
}

# ── Push-only mode (no rebuild) ──────────────────────────────────────────────
if [[ "$PUSH_ONLY" = "1" ]]; then
  _push_images
  exit 0
fi

# ── Build ─────────────────────────────────────────────────────────────────────
export CUDA_ARCH_BIN

echo ""
BAKE_FILE="$(dirname "${COMPOSE_FILE}")/docker-bake.hcl"

# Select bake group / targets
if [[ "$BUILD_ALL" = "1" && "$BUILD_DEV" = "1" ]]; then
  BAKE_TARGET="full"
elif [[ "$BUILD_ALL" = "1" ]]; then
  BAKE_TARGET="all"
else
  BAKE_TARGET="cap-y-base"
fi

if [[ "$BUILD_DEV" = "1" && "$BUILD_ALL" != "1" ]]; then
  BAKE_TARGET="cap-y-base cap-y-dev"
fi

echo "Building: ${BAKE_TARGET}  [arch=auto (TARGETARCH), cuda_arch=${CUDA_ARCH_BIN:-auto}]"
echo ""

LOG_FILE="/tmp/cap-y-build-$(date +%Y%m%d-%H%M%S).log"
echo "Build log: ${LOG_FILE}"
echo ""

CUDA_ARCH_BIN="${CUDA_ARCH_BIN}" WITH_DEMOGRASP="${WITH_DEMOGRASP:-1}" \
  docker buildx bake -f "${BAKE_FILE}" ${BAKE_TARGET} \
  2>&1 | tee "${LOG_FILE}"

echo ""
echo "Built images:"
docker image ls cap-y

if [[ "$PUSH" = "1" ]]; then
  _push_images
fi
